title: Primera Github Page
author: Eduardo González Pérez
email: alu0101319001@ull.edu.es
description: > # this means to ignore newlines until "baseurl:"
  Creación de la primera page en Github. Aprendiendo a escribir ficheros .md 
  y ficheros de configuración .yml. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

# theme 
theme: minima
